#!/bin/bash
# Adds user and starts sshd
# Requires atleast SFTP_USER and SFTP_PASSWORD as environment variables set

user=$SFTP_USER
password=$SFTP_PASSWORD
uid=$SFTP_UID
gid=$SFTP_GID

useraddParams="-m -N"
if [ -n "$uid" ]; then
    useraddParams="$useraddParams -o -u $uid"
fi

if [ -n "$gid" ]; then
    useraddParams="$useraddParams -g $gid"
    groupadd -g $gid $gid
fi

useradd $useraddParams "$user"
chown root:root /home/$user
chmod 755 /home/$user

indir=/home/$user/IN
mkdir $indir
chmod 755 $indir
chown $user:users $indir

echo "$user:$password" | chpasswd

exec /usr/sbin/sshd -D
