#!/bin/bash
# Adds user and starts sshd
# Requires atleast SFTP_USER and SFTP_PASSWORD as environment variables set

user=$SFTP_USER
password=$SFTP_PASSWORD
uid=1001
gid=100

useraddParams="-m -N -o -u $uid -g $gid"
groupadd -g $gid $gid

useradd $useraddParams "$user"
chown root:root /home/$user
chmod 755 /home/$user

indir=/home/$user/IN
mkdir $indir
chmod 755 $indir
chown $user:users $indir

echo "$user:$password" | chpasswd

exec /usr/sbin/sshd -D
